# Generated by Django 3.1.3 on 2020-12-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mh_app', '0002_mhproprofile_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mhproprofile',
            name='id_num',
            field=models.IntegerField(default=0),
        ),
    ]
