# Generated by Django 3.1.3 on 2020-12-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mh_app', '0005_mhproprofile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='mhproprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mhproprofile',
            name='work_contact',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
