# Generated by Django 3.1.3 on 2020-12-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mh_app', '0007_auto_20201210_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mhproprofile',
            name='work_place_contact',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
