# Generated by Django 3.1.3 on 2020-12-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mh_app', '0008_auto_20201210_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mhproprofile',
            name='edu_level',
        ),
        migrations.AddField(
            model_name='mhproprofile',
            name='education_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
