# Generated by Django 3.1.3 on 2020-12-10 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mh_app', '0009_auto_20201210_0145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mhproprofile',
            old_name='id_num',
            new_name='id_number',
        ),
    ]
