# Generated by Django 3.1.3 on 2020-12-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mh_app', '0010_auto_20201210_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mhproprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='pics', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='pics', upload_to='uploads/'),
        ),
    ]
