# Generated by Django 3.1.3 on 2020-12-10 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mh_app', '0012_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings_out_of_10', models.DecimalField(decimal_places=2, max_digits=4)),
                ('overall', models.DecimalField(decimal_places=2, max_digits=4)),
                ('person_rated', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='mh_app.mhproprofile')),
                ('user_rating', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ratings_done', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_rating', 'person_rated')},
            },
        ),
    ]
